# Site settings
title: This is the title
subtitle: "Journal of myname"
email: r.liu.gbox@gmail.com
description: "Home to 猫大师 and Herr Giraffe"
baseurl: ""
url: "http://127.0.0.1"
#twitter_username: "rowanoulton"
github_username:  "lmodan"
#instagram_username: "rowanoulton"

#gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 1

# Sass
sass:
    style: :compressed
